### ISSUE TITLE
Search icon not showing

### ISSUE THREAD

**Issue by code-masala** [fiqryq/blog#1]
@fiqryq 
in docusaurus.config.js
` plugins: [require.resolve("@easyops-cn/docusaurus-search-local")]`
in package.json
```
 "@cmfcmf/docusaurus-search-local": "^0.6.6",
 "@easyops-cn/docusaurus-search-local": "^0.19.1",
```

what else i have to add plz help

**Comment by fiqryq** [comment]
That's all, you have to publish first if u want to try searchbar

**Comment by code-masala** [comment]
bro publish mean deploy?

**Comment by fiqryq** [comment]
yap

**Comment by code-masala** [comment]
bro can you plz tell me how it is related to deploy?

**Comment by fiqryq** [comment]
Search only works for the statically built documentation (i.e., after you ran yarn build in your documentation folder).
Search does not work in development (i.e., when running yarn start).

**Comment by code-masala** [comment]
@fiqryq i have clone your repo on my machine and it's working fine.

**Comment by fiqryq** [comment]
have u try on your project?

**Comment by code-masala** [comment]
Yes but no search bar appear

**Comment by fiqryq** [comment]
have u try to deploy your project? or you just run on local?

**Comment by code-masala** [comment]
running on the local host

**Comment by code-masala** [comment]
Search only works for the statically built documentation (i.e., after you ran yarn build in your documentation folder).
Search does not work in development (i.e., when running yarn start).
 for this working is different from apearing

**Comment by fiqryq** [comment]
just deploy using vercel and select docusaurus framework preset , its work for me
![Screen Shot 2021-11-08 at 19 31 30](https://user-images.githubusercontent.com/25787603/140742613-98b0d9d8-2f01-4255-9cd0-7e0f793493ac.png)
